name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: env GOOS=linux GOARCH=arm go build -v ./main.go -o ./main_arm
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: |
          ./main_arm
